export const menuData = {
  Countries: [
    { title: "Study in UK", href: "/countries/uk" },
    { title: "Study in Ireland", href: "/countries/ireland" },
    { title: "Study in USA", href: "/countries/usa" },
    { title: "Study in Canada", href: "/countries/canada" },
    { title: "Study in Germany", href: "/countries/germany" },
    { title: "Study in Australia", href: "/countries/australia" },
    { title: "Study in France", href: "/countries/france" },
    { title: "Study in Spain", href: "/countries/spain" },
    { title: "Study in Europe", href: "/countries/europe" },
    { title: "Study in New Zealand", href: "/countries/new-zealand" },
  ],
  "Test Prep": [
    { title: "IELTS", href: "/test-prep/ielts" },
    { title: "Duo Lingo", href: "/test-prep/duo-lingo" },
    { title: "PTE", href: "/test-prep/pte" },
    { title: "TOEFL", href: "/test-prep/toefl" },
    { title: "GRE", href: "/test-prep/gre" },
    { title: "GMAT", href: "/test-prep/gmat" },
    { title: "SAT", href: "/test-prep/sat" },
  ],
  Services: [
    { title: "About Us", href: "/services/about-us" },
    { title: "Scholarships", href: "/services/scholarships" },
    { title: "Our Services", href: "/services/our-services" },
    { title: "Testimonials & Reviews", href: "/services/testimonials" },
  ],
  Resources: [
    { title: "Blogs", href: "/resources/blogs" },
    { title: "Tools", href: "/resources/tools" },
    { title: "Expense Calculator", href: "/resources/expense-calculator" },
    { title: "Loan Calculator", href: "/resources/loan-calculator" },
    { title: "GPA Calculator", href: "/resources/gpa-calculator" },
    { title: "Refer & Earn", href: "/resources/refer-and-earn" },
    { title: "Alumni Connect", href: "/resources/alumni-connect" },
  ],
};

export const faqData = [
  {
    question: "Why should I hire study abroad consultant?",
    answer:
      "Hiring a study abroad consultant like LearnshackEdu provides you with expert guidance and support throughout the entire application process. We have in-depth knowledge of various universities, programs, and admission requirements. We can help you make informed decisions, maximize your chances of acceptance, and provide valuable insights on scholarships, visa processes, and accommodation. The difference is having an acceptance chance of 5% compared to that of 70%.",
  },
  {
    question: "Which country is the best for studying abroad?",
    answer:
      "The best country for studying abroad depends on your academic goals, budget, career aspirations, and personal preferences. Popular destinations include the USA, UK, Canada, Australia, Germany, and New Zealand. Each offers unique advantages in terms of education quality, post-study work opportunities, cultural experience, and cost of living.",
  },
  {
    question: "What Can I Expect In The Free Consultation Call?",
    answer:
      "In our free consultation call, we'll discuss your academic background, career goals, budget, preferred destinations, and timeline. We'll provide initial guidance on suitable programs and universities, explain the application process, and outline how our services can help you achieve your study abroad goals.",
  },
  {
    question:
      "Does the Indian government provide scholarships for studying abroad?",
    answer:
      "Yes, the Indian government offers several scholarship programs for students wishing to study abroad, including the National Overseas Scholarship, GATE Scholarship, and Commonwealth Scholarship. Additionally, various government departments and organizations like ICCR and UGC provide financial assistance for specific fields of study.",
  },
  {
    question:
      "How can a study abroad consultant help me choose the right university and program?",
    answer:
      "A study abroad consultant helps you select the right university and program by analyzing your academic profile, career goals, budget, and preferences. We provide insights on university rankings, program quality, admission requirements, and employment outcomes. We also consider factors like location, campus culture, and available support services to ensure a good fit.",
  },
];

export const progressCardData = [
  {
    title: "Students",
    desc: "mentored personally with 1:1 guidance across their full study abroad journey.",
    data: 3500,
    suffix: "+",
  },
  {
    title: "Scholarships",
    desc: "disbursed and fee waivers unlocked through strong, tailored applications.",
    data: 1.5,
    prefix: "₹",
    suffix: "Cr+",
    decimalPlaces: 1,
  },
  {
    title: "University Partners",
    desc: "across the UK, USA, Canada, Germany, Ireland, Australia, and more.",
    data: 850,
    suffix: "+",
  },
  {
    title: "Counsellings",
    desc: "and counting, with hundreds of new journeys beginning each month.",
    data: 25000,
    suffix: "+",
  },
];

export const reviewData = [
  {
    title: "Masters in Business Analyticsy",
    desc: "Learnshack helped me clear IELTS with 7.5 bands in just a month with clarity. They handled everything—from shortlisting top universities and submitting applications to securing my education loan and visa.",
    name: "Shubhra Pandey",
    from: "Banaras",
    to: "UK",
    flag: "🇬🇧",
    src: "/shubhra-pandey-withbg-learnshack.png",
  },
  {
    title: "MSc in Computer Science",
    desc: "I was working at the Times of India, but deep down, I felt stuck. On my friend's recommendation, I came to Learnshack. Their team didn’t just talk about universities; they helped me figure out my own goals and gave me the confidence to take this step. The entire process, from selecting the right university to getting my offer, was stress-free. Today, I’m here in the UK, studying at a world-class university and looking forward to my future.",
    name: "Sejal Arora",
    from: "Jhansi",
    to: "England",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    src: "/placeholder.png",
  },
  {
    title: "Msc in Medical Device Technology",
    desc: "I had already paid a deposit to a university in Ireland, but had to withdraw due to visa delays—waiting a year felt devastating. Then I found LearnShack. Their team truly understood my situation, gave me tailored advice, and I had a new offer letter within no time. Thanks to their relationships with universities, I didn’t have to waste a year, and today, I’m in Ireland, studying exactly what I wanted.",
    name: "Vignan Thokala",
    from: "Hyderabad",
    to: "Ireland",
    flag: "🇮🇪",
    src: "/vighnan-thokala-withbg-learnshack.png",
  },
  {
    title: "Msc Computer Science",
    desc: "Learnshack guided me from switching plans in India to securing admission at the University of Edinburgh with a scholarship and English test waiver. Their expert team understood my profile deeply and delivered results that felt truly personalized—even good enough for me to refer a friend confidently.",
    name: "Hrisav Raj",
    from: "Patna",
    to: "Scotland",
    flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    src: "/placeholder.png",
  },
  {
    title: "Msc in Cyber Security",
    desc: "I spent 3 lakhs on a premium study abroad service that failed to get me an admit or even recover my deposit. I felt completely lost—until I found LearnShack. They understood my goals, guided me personally, and even helped me get my refund back. More than just saving my money, they gave me a second chance at my dream.",
    name: "Keyur Sabhani",
    from: "Ahmedabad",
    to: "Germany",
    flag: "🇩🇪",
    src: "/keyur-sabhani-withbg-learnshack.png",
    featured: true,
  },
  {
    title: "MSc in Robotics & AI",
    desc: "I had multiple offers, but somehow, none of them felt right. My heart was set on the University of Hertfordshire, but getting in seemed nearly impossible. When I shared my goal with the counselors at Learnshack, instead of convincing me to settle for the options I already had, they worked towards making my dream a reality, and within just three days, I received my offer letter, along with a scholarship!",
    name: "Gautham Srinivasiah",
    from: "Hyderabad",
    to: "England",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    src: "/placeholder.png",
  },
  {
    title: "Msc in Sustainable Supply Chain Management",
    desc: "While other consultancy pushed me towards mismatched options, Learnshack suggested better-suited countries like Ireland and USA. We applied to six universities & I got offers from literally all of them. Today, I’m studying my dream course at UCD, and I finally felt like someone was truly on my side.",
    name: "Himani Verma",
    from: "Delhi",
    to: "Ireland",
    flag: "🇮🇪",
    src: "/himani-verma-withbg-learnshack.png",
  },
  {
    title: "MSc in Computer Science",
    desc: "I was struggling to clear IELTS and TOEFL despite multiple attempts, even after paying a deposit elsewhere. Learnshack turned it all around—helping me find a university that waived English tests, securing a low-interest education loan, and even arranging my accommodation. Their support was a complete game-changer.",
    name: "Aradhya Charan",
    from: "Lucknow",
    to: "England",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    src: "/placeholder.png",
  },
  {
    title: "Msc in Artificial Intelligence",
    desc: "Learnshack helped me turn things around when my initial university and visa process got stuck. They guided me to withdraw the old application, secured my admit to Aston University, and helped me file a priority visa within weeks.",
    name: "Harsh Jirapure",
    from: "Surat",
    to: "UK",
    flag: "🇬🇧",
    src: "/harsh-jirapure-withbg-learnshack.png",
  },
];

export const countries = [
  {
    code: "AF",
    name: "Afghanistan",
    phoneCode: "+93",
    flag: "🇦🇫",
    maxNumberLength: 9,
  },
  {
    code: "AL",
    name: "Albania",
    phoneCode: "+355",
    flag: "🇦🇱",
    maxNumberLength: 9,
  },
  {
    code: "DZ",
    name: "Algeria",
    phoneCode: "+213",
    flag: "🇩🇿",
    maxNumberLength: 9,
  },
  {
    code: "AS",
    name: "American Samoa",
    phoneCode: "+1-684",
    flag: "🇦🇸",
    maxNumberLength: 10,
  },
  {
    code: "AD",
    name: "Andorra",
    phoneCode: "+376",
    flag: "🇦🇩",
    maxNumberLength: 6,
  },
  {
    code: "AO",
    name: "Angola",
    phoneCode: "+244",
    flag: "🇦🇴",
    maxNumberLength: 9,
  },
  {
    code: "AI",
    name: "Anguilla",
    phoneCode: "+1-264",
    flag: "🇦🇮",
    maxNumberLength: 10,
  },
  {
    code: "AQ",
    name: "Antarctica",
    phoneCode: "+672",
    flag: "🇦🇶",
    maxNumberLength: 6,
  },
  {
    code: "AG",
    name: "Antigua and Barbuda",
    phoneCode: "+1-268",
    flag: "🇦🇬",
    maxNumberLength: 10,
  },
  {
    code: "AR",
    name: "Argentina",
    phoneCode: "+54",
    flag: "🇦🇷",
    maxNumberLength: 10,
  },
  {
    code: "AM",
    name: "Armenia",
    phoneCode: "+374",
    flag: "🇦🇲",
    maxNumberLength: 8,
  },
  {
    code: "AW",
    name: "Aruba",
    phoneCode: "+297",
    flag: "🇦🇼",
    maxNumberLength: 7,
  },
  {
    code: "AU",
    name: "Australia",
    phoneCode: "+61",
    flag: "🇦🇺",
    maxNumberLength: 9,
  },
  {
    code: "AT",
    name: "Austria",
    phoneCode: "+43",
    flag: "🇦🇹",
    maxNumberLength: 11,
  },
  {
    code: "AZ",
    name: "Azerbaijan",
    phoneCode: "+994",
    flag: "🇦🇿",
    maxNumberLength: 9,
  },
  {
    code: "BS",
    name: "Bahamas",
    phoneCode: "+1-242",
    flag: "🇧🇸",
    maxNumberLength: 10,
  },
  {
    code: "BH",
    name: "Bahrain",
    phoneCode: "+973",
    flag: "🇧🇭",
    maxNumberLength: 8,
  },
  {
    code: "BD",
    name: "Bangladesh",
    phoneCode: "+880",
    flag: "🇧🇩",
    maxNumberLength: 10,
  },
  {
    code: "BB",
    name: "Barbados",
    phoneCode: "+1-246",
    flag: "🇧🇧",
    maxNumberLength: 10,
  },
  {
    code: "BY",
    name: "Belarus",
    phoneCode: "+375",
    flag: "🇧🇾",
    maxNumberLength: 9,
  },
  {
    code: "BE",
    name: "Belgium",
    phoneCode: "+32",
    flag: "🇧🇪",
    maxNumberLength: 9,
  },
  {
    code: "BZ",
    name: "Belize",
    phoneCode: "+501",
    flag: "🇧🇿",
    maxNumberLength: 7,
  },
  {
    code: "BJ",
    name: "Benin",
    phoneCode: "+229",
    flag: "🇧🇯",
    maxNumberLength: 8,
  },
  {
    code: "BM",
    name: "Bermuda",
    phoneCode: "+1-441",
    flag: "🇧🇲",
    maxNumberLength: 10,
  },
  {
    code: "BT",
    name: "Bhutan",
    phoneCode: "+975",
    flag: "🇧🇹",
    maxNumberLength: 8,
  },
  {
    code: "BO",
    name: "Bolivia",
    phoneCode: "+591",
    flag: "🇧🇴",
    maxNumberLength: 8,
  },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    phoneCode: "+387",
    flag: "🇧🇦",
    maxNumberLength: 8,
  },
  {
    code: "BW",
    name: "Botswana",
    phoneCode: "+267",
    flag: "🇧🇼",
    maxNumberLength: 8,
  },
  {
    code: "BV",
    name: "Bouvet Island",
    phoneCode: "+47",
    flag: "🇧🇻",
    maxNumberLength: 8,
  },
  {
    code: "BR",
    name: "Brazil",
    phoneCode: "+55",
    flag: "🇧🇷",
    maxNumberLength: 11,
  },
  {
    code: "IO",
    name: "British Indian Ocean Territory",
    phoneCode: "+246",
    flag: "🇮🇴",
    maxNumberLength: 7,
  },
  {
    code: "BN",
    name: "Brunei",
    phoneCode: "+673",
    flag: "🇧🇳",
    maxNumberLength: 7,
  },
  {
    code: "BG",
    name: "Bulgaria",
    phoneCode: "+359",
    flag: "🇧🇬",
    maxNumberLength: 9,
  },
  {
    code: "BF",
    name: "Burkina Faso",
    phoneCode: "+226",
    flag: "🇧🇫",
    maxNumberLength: 8,
  },
  {
    code: "BI",
    name: "Burundi",
    phoneCode: "+257",
    flag: "🇧🇮",
    maxNumberLength: 8,
  },
  {
    code: "KH",
    name: "Cambodia",
    phoneCode: "+855",
    flag: "🇰🇭",
    maxNumberLength: 9,
  },
  {
    code: "CM",
    name: "Cameroon",
    phoneCode: "+237",
    flag: "🇨🇲",
    maxNumberLength: 9,
  },
  {
    code: "CA",
    name: "Canada",
    phoneCode: "+1",
    flag: "🇨🇦",
    maxNumberLength: 10,
  },
  {
    code: "CV",
    name: "Cape Verde",
    phoneCode: "+238",
    flag: "🇨🇻",
    maxNumberLength: 7,
  },
  {
    code: "KY",
    name: "Cayman Islands",
    phoneCode: "+1-345",
    flag: "🇰🇾",
    maxNumberLength: 10,
  },
  {
    code: "CF",
    name: "Central African Republic",
    phoneCode: "+236",
    flag: "🇨🇫",
    maxNumberLength: 8,
  },
  {
    code: "TD",
    name: "Chad",
    phoneCode: "+235",
    flag: "🇹🇩",
    maxNumberLength: 8,
  },
  {
    code: "CL",
    name: "Chile",
    phoneCode: "+56",
    flag: "🇨🇱",
    maxNumberLength: 9,
  },
  {
    code: "CN",
    name: "China",
    phoneCode: "+86",
    flag: "🇨🇳",
    maxNumberLength: 11,
  },
  {
    code: "CX",
    name: "Christmas Island",
    phoneCode: "+61",
    flag: "🇨🇽",
    maxNumberLength: 9,
  },
  {
    code: "CC",
    name: "Cocos (Keeling) Islands",
    phoneCode: "+61",
    flag: "🇨🇨",
    maxNumberLength: 9,
  },
  {
    code: "CO",
    name: "Colombia",
    phoneCode: "+57",
    flag: "🇨🇴",
    maxNumberLength: 10,
  },
  {
    code: "KM",
    name: "Comoros",
    phoneCode: "+269",
    flag: "🇰🇲",
    maxNumberLength: 7,
  },
  {
    code: "CG",
    name: "Republic of the Congo",
    phoneCode: "+242",
    flag: "🇨🇬",
    maxNumberLength: 9,
  },
  {
    code: "CD",
    name: "Democratic Republic of the Congo",
    phoneCode: "+243",
    flag: "🇨🇩",
    maxNumberLength: 9,
  },
  {
    code: "CK",
    name: "Cook Islands",
    phoneCode: "+682",
    flag: "🇨🇰",
    maxNumberLength: 5,
  },
  {
    code: "CR",
    name: "Costa Rica",
    phoneCode: "+506",
    flag: "🇨🇷",
    maxNumberLength: 8,
  },
  {
    code: "CI",
    name: "Côte d'Ivoire",
    phoneCode: "+225",
    flag: "🇨🇮",
    maxNumberLength: 8,
  },
  {
    code: "HR",
    name: "Croatia",
    phoneCode: "+385",
    flag: "🇭🇷",
    maxNumberLength: 9,
  },
  {
    code: "CU",
    name: "Cuba",
    phoneCode: "+53",
    flag: "🇨🇺",
    maxNumberLength: 8,
  },
  {
    code: "CW",
    name: "Curaçao",
    phoneCode: "+599",
    flag: "🇨🇼",
    maxNumberLength: 7,
  },
  {
    code: "CY",
    name: "Cyprus",
    phoneCode: "+357",
    flag: "🇨🇾",
    maxNumberLength: 8,
  },
  {
    code: "CZ",
    name: "Czech Republic",
    phoneCode: "+420",
    flag: "🇨🇿",
    maxNumberLength: 9,
  },
  {
    code: "DK",
    name: "Denmark",
    phoneCode: "+45",
    flag: "🇩🇰",
    maxNumberLength: 8,
  },
  {
    code: "DJ",
    name: "Djibouti",
    phoneCode: "+253",
    flag: "🇩🇯",
    maxNumberLength: 8,
  },
  {
    code: "DM",
    name: "Dominica",
    phoneCode: "+1-767",
    flag: "🇩🇲",
    maxNumberLength: 10,
  },
  {
    code: "DO",
    name: "Dominican Republic",
    phoneCode: "+1-809, +1-829, +1-849",
    flag: "🇩🇴",
    maxNumberLength: 10,
  },
  {
    code: "EC",
    name: "Ecuador",
    phoneCode: "+593",
    flag: "🇪🇨",
    maxNumberLength: 9,
  },
  {
    code: "EG",
    name: "Egypt",
    phoneCode: "+20",
    flag: "🇪🇬",
    maxNumberLength: 10,
  },
  {
    code: "SV",
    name: "El Salvador",
    phoneCode: "+503",
    flag: "🇸🇻",
    maxNumberLength: 8,
  },
  {
    code: "GQ",
    name: "Equatorial Guinea",
    phoneCode: "+240",
    flag: "🇬🇶",
    maxNumberLength: 9,
  },
  {
    code: "ER",
    name: "Eritrea",
    phoneCode: "+291",
    flag: "🇪🇷",
    maxNumberLength: 7,
  },
  {
    code: "EE",
    name: "Estonia",
    phoneCode: "+372",
    flag: "🇪🇪",
    maxNumberLength: 8,
  },
  {
    code: "ET",
    name: "Ethiopia",
    phoneCode: "+251",
    flag: "🇪🇹",
    maxNumberLength: 9,
  },
  {
    code: "FK",
    name: "Falkland Islands",
    phoneCode: "+500",
    flag: "🇫🇰",
    maxNumberLength: 5,
  },
  {
    code: "FO",
    name: "Faroe Islands",
    phoneCode: "+298",
    flag: "🇫🇴",
    maxNumberLength: 6,
  },
  {
    code: "FJ",
    name: "Fiji",
    phoneCode: "+679",
    flag: "🇫🇯",
    maxNumberLength: 7,
  },
  {
    code: "FI",
    name: "Finland",
    phoneCode: "+358",
    flag: "🇫🇮",
    maxNumberLength: 10,
  },
  {
    code: "FR",
    name: "France",
    phoneCode: "+33",
    flag: "🇫🇷",
    maxNumberLength: 9,
  },
  {
    code: "GF",
    name: "French Guiana",
    phoneCode: "+594",
    flag: "🇬🇫",
    maxNumberLength: 9,
  },
  {
    code: "PF",
    name: "French Polynesia",
    phoneCode: "+689",
    flag: "🇵🇫",
    maxNumberLength: 6,
  },
  {
    code: "TF",
    name: "French Southern Territories",
    phoneCode: "+262",
    flag: "🇹🇫",
    maxNumberLength: 9,
  },
  {
    code: "GA",
    name: "Gabon",
    phoneCode: "+241",
    flag: "🇬🇦",
    maxNumberLength: 7,
  },
  {
    code: "GM",
    name: "Gambia",
    phoneCode: "+220",
    flag: "🇬🇲",
    maxNumberLength: 7,
  },
  {
    code: "GE",
    name: "Georgia",
    phoneCode: "+995",
    flag: "🇬🇪",
    maxNumberLength: 9,
  },
  {
    code: "DE",
    name: "Germany",
    phoneCode: "+49",
    flag: "🇩🇪",
    maxNumberLength: 11,
  },
  {
    code: "GH",
    name: "Ghana",
    phoneCode: "+233",
    flag: "🇬🇭",
    maxNumberLength: 9,
  },
  {
    code: "GI",
    name: "Gibraltar",
    phoneCode: "+350",
    flag: "🇬🇮",
    maxNumberLength: 8,
  },
  {
    code: "GR",
    name: "Greece",
    phoneCode: "+30",
    flag: "🇬🇷",
    maxNumberLength: 10,
  },
  {
    code: "GL",
    name: "Greenland",
    phoneCode: "+299",
    flag: "🇬🇱",
    maxNumberLength: 6,
  },
  {
    code: "GD",
    name: "Grenada",
    phoneCode: "+1-473",
    flag: "🇬🇩",
    maxNumberLength: 10,
  },
  {
    code: "GP",
    name: "Guadeloupe",
    phoneCode: "+590",
    flag: "🇬🇵",
    maxNumberLength: 9,
  },
  {
    code: "GU",
    name: "Guam",
    phoneCode: "+1-671",
    flag: "🇬🇺",
    maxNumberLength: 10,
  },
  {
    code: "GT",
    name: "Guatemala",
    phoneCode: "+502",
    flag: "🇬🇹",
    maxNumberLength: 8,
  },
  {
    code: "GG",
    name: "Guernsey",
    phoneCode: "+44-1481",
    flag: "🇬🇬",
    maxNumberLength: 10,
  },
  {
    code: "GN",
    name: "Guinea",
    phoneCode: "+224",
    flag: "🇬🇳",
    maxNumberLength: 9,
  },
  {
    code: "GW",
    name: "Guinea-Bissau",
    phoneCode: "+245",
    flag: "🇬🇼",
    maxNumberLength: 7,
  },
  {
    code: "GY",
    name: "Guyana",
    phoneCode: "+592",
    flag: "🇬🇾",
    maxNumberLength: 7,
  },
  {
    code: "HT",
    name: "Haiti",
    phoneCode: "+509",
    flag: "🇭🇹",
    maxNumberLength: 8,
  },
  {
    code: "HM",
    name: "Heard Island and McDonald Islands",
    phoneCode: "+672",
    flag: "🇭🇲",
    maxNumberLength: 6,
  },
  {
    code: "VA",
    name: "Holy See",
    phoneCode: "+39-06",
    flag: "🇻🇦",
    maxNumberLength: 10,
  },
  {
    code: "HN",
    name: "Honduras",
    phoneCode: "+504",
    flag: "🇭🇳",
    maxNumberLength: 8,
  },
  {
    code: "HK",
    name: "Hong Kong",
    phoneCode: "+852",
    flag: "🇭🇰",
    maxNumberLength: 8,
  },
  {
    code: "HU",
    name: "Hungary",
    phoneCode: "+36",
    flag: "🇭🇺",
    maxNumberLength: 9,
  },
  {
    code: "IS",
    name: "Iceland",
    phoneCode: "+354",
    flag: "🇮🇸",
    maxNumberLength: 7,
  },
  {
    code: "IN",
    name: "India",
    phoneCode: "+91",
    flag: "🇮🇳",
    maxNumberLength: 10,
  },
  {
    code: "ID",
    name: "Indonesia",
    phoneCode: "+62",
    flag: "🇮🇩",
    maxNumberLength: 12,
  },
  {
    code: "IR",
    name: "Iran",
    phoneCode: "+98",
    flag: "🇮🇷",
    maxNumberLength: 10,
  },
  {
    code: "IQ",
    name: "Iraq",
    phoneCode: "+964",
    flag: "🇮🇶",
    maxNumberLength: 10,
  },
  {
    code: "IE",
    name: "Ireland",
    phoneCode: "+353",
    flag: "🇮🇪",
    maxNumberLength: 9,
  },
  {
    code: "IM",
    name: "Isle of Man",
    phoneCode: "+44-1624",
    flag: "🇮🇲",
    maxNumberLength: 10,
  },
  {
    code: "IL",
    name: "Israel",
    phoneCode: "+972",
    flag: "🇮🇱",
    maxNumberLength: 9,
  },
  {
    code: "IT",
    name: "Italy",
    phoneCode: "+39",
    flag: "🇮🇹",
    maxNumberLength: 10,
  },
  {
    code: "JM",
    name: "Jamaica",
    phoneCode: "+1-876",
    flag: "🇯🇲",
    maxNumberLength: 10,
  },
  {
    code: "JP",
    name: "Japan",
    phoneCode: "+81",
    flag: "🇯🇵",
    maxNumberLength: 10,
  },
  {
    code: "JE",
    name: "Jersey",
    phoneCode: "+44-1534",
    flag: "🇯🇪",
    maxNumberLength: 10,
  },
  {
    code: "JO",
    name: "Jordan",
    phoneCode: "+962",
    flag: "🇯🇴",
    maxNumberLength: 9,
  },
  {
    code: "KZ",
    name: "Kazakhstan",
    phoneCode: "+7",
    flag: "🇰🇿",
    maxNumberLength: 10,
  },
  {
    code: "KE",
    name: "Kenya",
    phoneCode: "+254",
    flag: "🇰🇪",
    maxNumberLength: 9,
  },
  {
    code: "KI",
    name: "Kiribati",
    phoneCode: "+686",
    flag: "🇰🇮",
    maxNumberLength: 5,
  },
  {
    code: "KP",
    name: "North Korea",
    phoneCode: "+850",
    flag: "🇰🇵",
    maxNumberLength: 10,
  },
  {
    code: "KR",
    name: "South Korea",
    phoneCode: "+82",
    flag: "🇰🇷",
    maxNumberLength: 11,
  },
  {
    code: "KW",
    name: "Kuwait",
    phoneCode: "+965",
    flag: "🇰🇼",
    maxNumberLength: 8,
  },
  {
    code: "KG",
    name: "Kyrgyzstan",
    phoneCode: "+996",
    flag: "🇰🇬",
    maxNumberLength: 9,
  },
  {
    code: "LA",
    name: "Laos",
    phoneCode: "+856",
    flag: "🇱🇦",
    maxNumberLength: 10,
  },
  {
    code: "LV",
    name: "Latvia",
    phoneCode: "+371",
    flag: "🇱🇻",
    maxNumberLength: 8,
  },
  {
    code: "LB",
    name: "Lebanon",
    phoneCode: "+961",
    flag: "🇱🇧",
    maxNumberLength: 8,
  },
  {
    code: "LS",
    name: "Lesotho",
    phoneCode: "+266",
    flag: "🇱🇸",
    maxNumberLength: 8,
  },
  {
    code: "LR",
    name: "Liberia",
    phoneCode: "+231",
    flag: "🇱🇷",
    maxNumberLength: 8,
  },
  {
    code: "LY",
    name: "Libya",
    phoneCode: "+218",
    flag: "🇱🇾",
    maxNumberLength: 10,
  },
  {
    code: "LI",
    name: "Liechtenstein",
    phoneCode: "+423",
    flag: "🇱🇮",
    maxNumberLength: 7,
  },
  {
    code: "LT",
    name: "Lithuania",
    phoneCode: "+370",
    flag: "🇱🇹",
    maxNumberLength: 8,
  },
  {
    code: "LU",
    name: "Luxembourg",
    phoneCode: "+352",
    flag: "🇱🇺",
    maxNumberLength: 9,
  },
  {
    code: "MO",
    name: "Macao",
    phoneCode: "+853",
    flag: "🇲🇴",
    maxNumberLength: 8,
  },
  {
    code: "MK",
    name: "North Macedonia",
    phoneCode: "+389",
    flag: "🇲🇰",
    maxNumberLength: 8,
  },
  {
    code: "MG",
    name: "Madagascar",
    phoneCode: "+261",
    flag: "🇲🇬",
    maxNumberLength: 9,
  },
  {
    code: "MW",
    name: "Malawi",
    phoneCode: "+265",
    flag: "🇲🇼",
    maxNumberLength: 9,
  },
  {
    code: "MY",
    name: "Malaysia",
    phoneCode: "+60",
    flag: "🇲🇾",
    maxNumberLength: 10,
  },
  {
    code: "MV",
    name: "Maldives",
    phoneCode: "+960",
    flag: "🇲🇻",
    maxNumberLength: 7,
  },
  {
    code: "ML",
    name: "Mali",
    phoneCode: "+223",
    flag: "🇲🇱",
    maxNumberLength: 8,
  },
  {
    code: "MT",
    name: "Malta",
    phoneCode: "+356",
    flag: "🇲🇹",
    maxNumberLength: 8,
  },
  {
    code: "MH",
    name: "Marshall Islands",
    phoneCode: "+692",
    flag: "🇲🇭",
    maxNumberLength: 7,
  },
  {
    code: "MQ",
    name: "Martinique",
    phoneCode: "+596",
    flag: "🇲🇶",
    maxNumberLength: 9,
  },
  {
    code: "MR",
    name: "Mauritania",
    phoneCode: "+222",
    flag: "🇲🇷",
    maxNumberLength: 8,
  },
  {
    code: "MU",
    name: "Mauritius",
    phoneCode: "+230",
    flag: "🇲🇺",
    maxNumberLength: 8,
  },
  {
    code: "YT",
    name: "Mayotte",
    phoneCode: "+262",
    flag: "🇾🇹",
    maxNumberLength: 9,
  },
  {
    code: "MX",
    name: "Mexico",
    phoneCode: "+52",
    flag: "🇲🇽",
    maxNumberLength: 10,
  },
  {
    code: "FM",
    name: "Micronesia",
    phoneCode: "+691",
    flag: "🇫🇲",
    maxNumberLength: 7,
  },
  {
    code: "MD",
    name: "Moldova",
    phoneCode: "+373",
    flag: "🇲🇩",
    maxNumberLength: 8,
  },
  {
    code: "MC",
    name: "Monaco",
    phoneCode: "+377",
    flag: "🇲🇨",
    maxNumberLength: 8,
  },
  {
    code: "MN",
    name: "Mongolia",
    phoneCode: "+976",
    flag: "🇲🇳",
    maxNumberLength: 8,
  },
  {
    code: "ME",
    name: "Montenegro",
    phoneCode: "+382",
    flag: "🇲🇪",
    maxNumberLength: 8,
  },
  {
    code: "MS",
    name: "Montserrat",
    phoneCode: "+1-664",
    flag: "🇲🇸",
    maxNumberLength: 10,
  },
  {
    code: "MA",
    name: "Morocco",
    phoneCode: "+212",
    flag: "🇲🇦",
    maxNumberLength: 9,
  },
  {
    code: "MZ",
    name: "Mozambique",
    phoneCode: "+258",
    flag: "🇲🇿",
    maxNumberLength: 9,
  },
  {
    code: "MM",
    name: "Myanmar",
    phoneCode: "+95",
    flag: "🇲🇲",
    maxNumberLength: 10,
  },
  {
    code: "NA",
    name: "Namibia",
    phoneCode: "+264",
    flag: "🇳🇦",
    maxNumberLength: 9,
  },
  {
    code: "NR",
    name: "Nauru",
    phoneCode: "+674",
    flag: "🇳🇷",
    maxNumberLength: 7,
  },
  {
    code: "NP",
    name: "Nepal",
    phoneCode: "+977",
    flag: "🇳🇵",
    maxNumberLength: 10,
  },
  {
    code: "NL",
    name: "Netherlands",
    phoneCode: "+31",
    flag: "🇳🇱",
    maxNumberLength: 9,
  },
  {
    code: "NC",
    name: "New Caledonia",
    phoneCode: "+687",
    flag: "🇳🇨",
    maxNumberLength: 6,
  },
  {
    code: "NZ",
    name: "New Zealand",
    phoneCode: "+64",
    flag: "🇳🇿",
    maxNumberLength: 10,
  },
  {
    code: "NI",
    name: "Nicaragua",
    phoneCode: "+505",
    flag: "🇳🇮",
    maxNumberLength: 8,
  },
  {
    code: "NE",
    name: "Niger",
    phoneCode: "+227",
    flag: "🇳🇪",
    maxNumberLength: 8,
  },
  {
    code: "NG",
    name: "Nigeria",
    phoneCode: "+234",
    flag: "🇳🇬",
    maxNumberLength: 10,
  },
  {
    code: "NU",
    name: "Niue",
    phoneCode: "+683",
    flag: "🇳🇺",
    maxNumberLength: 4,
  },
  {
    code: "NF",
    name: "Norfolk Island",
    phoneCode: "+672",
    flag: "🇳🇫",
    maxNumberLength: 6,
  },
  {
    code: "MP",
    name: "Northern Mariana Islands",
    phoneCode: "+1-670",
    flag: "🇲🇵",
    maxNumberLength: 10,
  },
  {
    code: "NO",
    name: "Norway",
    phoneCode: "+47",
    flag: "🇳🇴",
    maxNumberLength: 8,
  },
  {
    code: "OM",
    name: "Oman",
    phoneCode: "+968",
    flag: "🇴🇲",
    maxNumberLength: 8,
  },
  {
    code: "PK",
    name: "Pakistan",
    phoneCode: "+92",
    flag: "🇵🇰",
    maxNumberLength: 10,
  },
  {
    code: "PW",
    name: "Palau",
    phoneCode: "+680",
    flag: "🇵🇼",
    maxNumberLength: 7,
  },
  {
    code: "PS",
    name: "Palestine",
    phoneCode: "+970",
    flag: "🇵🇸",
    maxNumberLength: 9,
  },
  {
    code: "PA",
    name: "Panama",
    phoneCode: "+507",
    flag: "🇵🇦",
    maxNumberLength: 8,
  },
  {
    code: "PG",
    name: "Papua New Guinea",
    phoneCode: "+675",
    flag: "🇵🇬",
    maxNumberLength: 8,
  },
  {
    code: "PY",
    name: "Paraguay",
    phoneCode: "+595",
    flag: "🇵🇾",
    maxNumberLength: 9,
  },
  {
    code: "PE",
    name: "Peru",
    phoneCode: "+51",
    flag: "🇵🇪",
    maxNumberLength: 9,
  },
  {
    code: "PH",
    name: "Philippines",
    phoneCode: "+63",
    flag: "🇵🇭",
    maxNumberLength: 10,
  },
  {
    code: "PN",
    name: "Pitcairn",
    phoneCode: "+64",
    flag: "🇵🇳",
    maxNumberLength: 10,
  },
  {
    code: "PL",
    name: "Poland",
    phoneCode: "+48",
    flag: "🇵🇱",
    maxNumberLength: 9,
  },
  {
    code: "PT",
    name: "Portugal",
    phoneCode: "+351",
    flag: "🇵🇹",
    maxNumberLength: 9,
  },
  {
    code: "PR",
    name: "Puerto Rico",
    phoneCode: "+1-787, +1-939",
    flag: "🇵🇷",
    maxNumberLength: 10,
  },
  {
    code: "QA",
    name: "Qatar",
    phoneCode: "+974",
    flag: "🇶🇦",
    maxNumberLength: 8,
  },
  {
    code: "RE",
    name: "Réunion",
    phoneCode: "+262",
    flag: "🇷🇪",
    maxNumberLength: 9,
  },
  {
    code: "RO",
    name: "Romania",
    phoneCode: "+40",
    flag: "🇷🇴",
    maxNumberLength: 9,
  },
  {
    code: "RU",
    name: "Russia",
    phoneCode: "+7",
    flag: "🇷🇺",
    maxNumberLength: 10,
  },
  {
    code: "RW",
    name: "Rwanda",
    phoneCode: "+250",
    flag: "🇷🇼",
    maxNumberLength: 9,
  },
  {
    code: "BL",
    name: "Saint Barthélemy",
    phoneCode: "+590",
    flag: "🇧🇱",
    maxNumberLength: 9,
  },
  {
    code: "SH",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    phoneCode: "+290",
    flag: "🇸🇭",
    maxNumberLength: 5,
  },
  {
    code: "KN",
    name: "Saint Kitts and Nevis",
    phoneCode: "+1-869",
    flag: "🇰🇳",
    maxNumberLength: 10,
  },
  {
    code: "LC",
    name: "Saint Lucia",
    phoneCode: "+1-758",
    flag: "🇱🇨",
    maxNumberLength: 10,
  },
  {
    code: "MF",
    name: "Saint Martin (French part)",
    phoneCode: "+590",
    flag: "🇲🇫",
    maxNumberLength: 9,
  },
  {
    code: "PM",
    name: "Saint Pierre and Miquelon",
    phoneCode: "+508",
    flag: "🇵🇲",
    maxNumberLength: 6,
  },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    phoneCode: "+1-784",
    flag: "🇻🇨",
    maxNumberLength: 10,
  },
  {
    code: "WS",
    name: "Samoa",
    phoneCode: "+685",
    flag: "🇼🇸",
    maxNumberLength: 7,
  },
  {
    code: "SM",
    name: "San Marino",
    phoneCode: "+378",
    flag: "🇸🇲",
    maxNumberLength: 8,
  },
  {
    code: "ST",
    name: "Sao Tome and Principe",
    phoneCode: "+239",
    flag: "🇸🇹",
    maxNumberLength: 7,
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    phoneCode: "+966",
    flag: "🇸🇦",
    maxNumberLength: 9,
  },
  {
    code: "SN",
    name: "Senegal",
    phoneCode: "+221",
    flag: "🇸🇳",
    maxNumberLength: 9,
  },
  {
    code: "RS",
    name: "Serbia",
    phoneCode: "+381",
    flag: "🇷🇸",
    maxNumberLength: 9,
  },
  {
    code: "SC",
    name: "Seychelles",
    phoneCode: "+248",
    flag: "🇸🇨",
    maxNumberLength: 7,
  },
  {
    code: "SL",
    name: "Sierra Leone",
    phoneCode: "+232",
    flag: "🇸🇱",
    maxNumberLength: 8,
  },
  {
    code: "SG",
    name: "Singapore",
    phoneCode: "+65",
    flag: "🇸🇬",
    maxNumberLength: 8,
  },
  {
    code: "SX",
    name: "Sint Maarten (Dutch part)",
    phoneCode: "+1-721",
    flag: "🇸🇽",
    maxNumberLength: 10,
  },
  {
    code: "SK",
    name: "Slovakia",
    phoneCode: "+421",
    flag: "🇸🇰",
    maxNumberLength: 9,
  },
  {
    code: "SI",
    name: "Slovenia",
    phoneCode: "+386",
    flag: "🇸🇮",
    maxNumberLength: 8,
  },
  {
    code: "SB",
    name: "Solomon Islands",
    phoneCode: "+677",
    flag: "🇸🇧",
    maxNumberLength: 7,
  },
  {
    code: "SO",
    name: "Somalia",
    phoneCode: "+252",
    flag: "🇸🇴",
    maxNumberLength: 8,
  },
  {
    code: "ZA",
    name: "South Africa",
    phoneCode: "+27",
    flag: "🇿🇦",
    maxNumberLength: 9,
  },
  {
    code: "GS",
    name: "South Georgia and the South Sandwich Islands",
    phoneCode: "+500",
    flag: "🇬🇸",
    maxNumberLength: 5,
  },
  {
    code: "SS",
    name: "South Sudan",
    phoneCode: "+211",
    flag: "🇸🇸",
    maxNumberLength: 9,
  },
  {
    code: "ES",
    name: "Spain",
    phoneCode: "+34",
    flag: "🇪🇸",
    maxNumberLength: 9,
  },
  {
    code: "LK",
    name: "Sri Lanka",
    phoneCode: "+94",
    flag: "🇱🇰",
    maxNumberLength: 9,
  },
  {
    code: "SD",
    name: "Sudan",
    phoneCode: "+249",
    flag: "🇸🇩",
    maxNumberLength: 9,
  },
  {
    code: "SR",
    name: "Suriname",
    phoneCode: "+597",
    flag: "🇸🇷",
    maxNumberLength: 7,
  },
  {
    code: "SJ",
    name: "Svalbard and Jan Mayen",
    phoneCode: "+47",
    flag: "🇸🇯",
    maxNumberLength: 8,
  },
  {
    code: "SZ",
    name: "Eswatini",
    phoneCode: "+268",
    flag: "🇸🇿",
    maxNumberLength: 8,
  },
  {
    code: "SE",
    name: "Sweden",
    phoneCode: "+46",
    flag: "🇸🇪",
    maxNumberLength: 9,
  },
  {
    code: "CH",
    name: "Switzerland",
    phoneCode: "+41",
    flag: "🇨🇭",
    maxNumberLength: 9,
  },
  {
    code: "SY",
    name: "Syria",
    phoneCode: "+963",
    flag: "🇸🇾",
    maxNumberLength: 9,
  },
  {
    code: "TW",
    name: "Taiwan",
    phoneCode: "+886",
    flag: "🇹🇼",
    maxNumberLength: 9,
  },
  {
    code: "TJ",
    name: "Tajikistan",
    phoneCode: "+992",
    flag: "🇹🇯",
    maxNumberLength: 9,
  },
  {
    code: "TZ",
    name: "Tanzania",
    phoneCode: "+255",
    flag: "🇹🇿",
    maxNumberLength: 9,
  },
  {
    code: "TH",
    name: "Thailand",
    phoneCode: "+66",
    flag: "🇹🇭",
    maxNumberLength: 9,
  },
  {
    code: "TL",
    name: "Timor-Leste",
    phoneCode: "+670",
    flag: "🇹🇱",
    maxNumberLength: 8,
  },
  {
    code: "TG",
    name: "Togo",
    phoneCode: "+228",
    flag: "🇹🇬",
    maxNumberLength: 8,
  },
  {
    code: "TK",
    name: "Tokelau",
    phoneCode: "+690",
    flag: "🇹🇰",
    maxNumberLength: 4,
  },
  {
    code: "TO",
    name: "Tonga",
    phoneCode: "+676",
    flag: "🇹🇴",
    maxNumberLength: 7,
  },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    phoneCode: "+1-868",
    flag: "🇹🇹",
    maxNumberLength: 10,
  },
  {
    code: "TN",
    name: "Tunisia",
    phoneCode: "+216",
    flag: "🇹🇳",
    maxNumberLength: 8,
  },
  {
    code: "TR",
    name: "Turkey",
    phoneCode: "+90",
    flag: "🇹🇷",
    maxNumberLength: 10,
  },
  {
    code: "TM",
    name: "Turkmenistan",
    phoneCode: "+993",
    flag: "🇹🇲",
    maxNumberLength: 8,
  },
  {
    code: "TC",
    name: "Turks and Caicos Islands",
    phoneCode: "+1-649",
    flag: "🇹🇨",
    maxNumberLength: 10,
  },
  {
    code: "TV",
    name: "Tuvalu",
    phoneCode: "+688",
    flag: "🇹🇻",
    maxNumberLength: 5,
  },
  {
    code: "UG",
    name: "Uganda",
    phoneCode: "+256",
    flag: "🇺🇬",
    maxNumberLength: 9,
  },
  {
    code: "UA",
    name: "Ukraine",
    phoneCode: "+380",
    flag: "🇺🇦",
    maxNumberLength: 9,
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    phoneCode: "+971",
    flag: "🇦🇪",
    maxNumberLength: 9,
  },
  {
    code: "GB",
    name: "United Kingdom",
    phoneCode: "+44",
    flag: "🇬🇧",
    maxNumberLength: 10,
  },
  {
    code: "US",
    name: "United States",
    phoneCode: "+1",
    flag: "🇺🇸",
    maxNumberLength: 10,
  },
  {
    code: "UM",
    name: "United States Minor Outlying Islands",
    phoneCode: "+1",
    flag: "🇺🇲",
    maxNumberLength: 10,
  },
  {
    code: "UY",
    name: "Uruguay",
    phoneCode: "+598",
    flag: "🇺🇾",
    maxNumberLength: 8,
  },
  {
    code: "UZ",
    name: "Uzbekistan",
    phoneCode: "+998",
    flag: "🇺🇿",
    maxNumberLength: 9,
  },
  {
    code: "VU",
    name: "Vanuatu",
    phoneCode: "+678",
    flag: "🇻🇺",
    maxNumberLength: 7,
  },
  {
    code: "VE",
    name: "Venezuela",
    phoneCode: "+58",
    flag: "🇻🇪",
    maxNumberLength: 10,
  },
  {
    code: "VN",
    name: "Vietnam",
    phoneCode: "+84",
    flag: "🇻🇳",
    maxNumberLength: 10,
  },
  {
    code: "VG",
    name: "Virgin Islands (British)",
    phoneCode: "+1-284",
    flag: "🇻🇬",
    maxNumberLength: 10,
  },
  {
    code: "VI",
    name: "Virgin Islands (U.S.)",
    phoneCode: "+1-340",
    flag: "🇻🇮",
    maxNumberLength: 10,
  },
  {
    code: "WF",
    name: "Wallis and Futuna",
    phoneCode: "+681",
    flag: "🇼🇫",
    maxNumberLength: 6,
  },
  {
    code: "EH",
    name: "Western Sahara",
    phoneCode: "+212",
    flag: "🇪🇭",
    maxNumberLength: 9,
  },
  {
    code: "YE",
    name: "Yemen",
    phoneCode: "+967",
    flag: "🇾🇪",
    maxNumberLength: 9,
  },
  {
    code: "ZM",
    name: "Zambia",
    phoneCode: "+260",
    flag: "🇿🇲",
    maxNumberLength: 9,
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    phoneCode: "+263",
    flag: "🇿🇼",
    maxNumberLength: 9,
  },
];
